<topicMap id="xtm-language"
   xmlns="http://www.topicmaps.org/xtm/1.0/"
   xmlns:xlink='http://www.w3.org/1999/xlink'> 

  <topic id="country">
    <subjectIdentity>
      <subjectIndicatorRef xlink:href="http://www.topicmaps.org/xtm/1.0/core.xtm#country"/>
    </subjectIdentity>

    <baseName>
      <baseNameString>Country</baseNameString>
      <variant>
        <parameters>
          <topicRef xlink:href="#swedish"/>
        </parameters>
        <variantName><resourceData>Land</resourceData></variantName>
      </variant>
    </baseName>    
  </topic>

  <topic id="swedish">
    <baseName>
      <baseNameString>Swedish</baseNameString>
    </baseName>
  </topic>

</topicMap>
