dist: trusty
sudo: required
language: java
install: true
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
env:
  global:
    - secure: "mr5Zw6RfbcRG6NVR1XCfOpi6ezCs6iAW3dMM3dVJ6Zyl4dSfSGxJlRr51UbXXcMlDMxeat/y5wu3cZae4Ay7/umPv8yTqnBTGk+Jr1SCVOxVvZVI1SBjE3+T/ASXWhzBLlFzDyEMt7QWeLJ4HD7mRSrU3646dhKjWkibHU9S7BT6IprV9KAOXZ5iBk3BHxiNMNuJwibZu1axHR2frVU6J6ELxHCQTQSX1QoVhsX60fPkHhTjmaXANXiN/iFA6VZ94jmi/klRKHUZ3bvpStAe2gB16aoiUvllIz3XrXZB7MISGoyT6x2bHLZZhjRGbe2JKBpLrFeLqinEdVHkCplWbrMBq35awePQHtL5FEr5rwSPhAVaIpDbH+AFz5AeA4onu+jd1j6ZoV4PmBv9wBcH33ZilB6SARkwuMdLQEAZAViAMJsGXC1oM/k1bnIilSeJTgqB0WcxWUafxjw6gMXWMbTgdlVWJdv+toRoP1nBPqh7YqLjv7EC4n/7nAmpKTi+e0+iqdFxJ7Rw9Hjd+VhpzRJR81/AD9s+LznW+ttDJm6PQvfU0SOVMXNI/tLAdE6tiHpH6dp0r/nBewdzdNLKBRqcIgSp4aOZOW5GdFmvEr3jTllqFlMWuVWtPXRZNUzpDtYb9lZnLhh4imgL9uavr7YXuDnjwV3h7AhkpLcB1Z4="
    - secure: "GgDC2zk52NHzYpbFNTOlkANiJpzbTotUKKuDhjq63JpojdnV7+ptT7bQqQrAOcW655FZQyqtHbopukI0xFqJ+HKH9AS/B7OwDSAMG7/K3G1J/QYUt1sk3YPetgIZkMe0YzSy3HwQLI25H3Y4neRXMjSZy9nbU5A+x/6E1i17mbkXrCwxrYCmPAdNTgfUT6sHUm0mbAtjMHXXi0P8Nkzih+3MJgKgqJ86GFzJBpjQoTHoE/OvLX+XeQ8jRQLdg9HYi0Z+yFJMxlsexhiQDI/phQR8469KqJI8Z8KlqGQ4A6kZ5IHIIjlbznyAJt3aYUgvcd132u7QQndlIUZoJDNrm4U9ZXGknwiT/JOPhOGrmywlCboHDLN8sCtsrUDE3pFL0syNgWGZVO1fJ97XuYAak3WcwR+yv8dsR5WnN8LoiRoUu+gMnY2kilS3sIbsKE514gyv8pmayWlC0ESnjBVuA4RCAuRLW7ErM8TyB2xtsSqXU1hBQ3m0/GF50kqI+XQyyOCsiw3PRVLB59+NjYHEhcwj+yFb7p4AY851WJhdytao+7OMx3pndEC8l0bQt6LrjZRXsWL/xPUaAah511qjijWrHtAbhzHcVjNbY1F4VIu4gMXOZLQ9cL+6TwZSqmhKL2jXCTi5gEzeMDPnsH2nxR3Mg+2sb+YzyFjePinZQLA="
jobs:
  include:
    - stage: "Dependencies"
      script: mvn -B -q dependency:go-offline
    - stage: build
      script: mvn -B clean deploy -Dontopia.jetty.port=9090 --settings .travis.settings.xml
