/* The following code was generated by JFlex 1.4.3 on 12/14/09 10:15 AM */


// $Id: ctm.flex,v 1.2 2009/04/27 11:04:17 lars.garshol Exp $

package net.ontopia.topicmaps.utils.ctm;

import antlr.*;
import net.ontopia.topicmaps.xml.InvalidTopicMapException;

// To get ANTLR token types generated for parser.

/**
 * A CTM lexer, to be used with the Antlr-generated parser.
 */

public class CTMLexer implements TokenStream {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\0\1\23"+
    "\1\4\1\14\1\33\2\0\1\5\1\6\1\27\1\26\1\56\1\13"+
    "\1\11\1\16\1\32\1\31\10\10\1\7\1\17\1\21\1\60\1\22"+
    "\1\64\1\57\6\24\15\12\1\30\1\67\5\12\1\62\1\65\1\20"+
    "\1\63\1\12\1\0\1\54\1\25\1\36\1\40\1\34\1\47\1\42"+
    "\1\15\1\41\1\15\1\55\1\51\1\53\1\35\1\37\1\46\1\15"+
    "\1\44\1\45\1\66\1\52\1\43\1\15\1\50\2\15\3\0\1\61"+
    "\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\1\1\10\1\12\1\13\1\1"+
    "\1\14\1\1\1\15\1\6\1\1\4\10\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\1"+
    "\2\0\1\6\3\0\1\6\1\27\11\0\4\10\1\30"+
    "\1\31\1\32\1\33\1\34\1\0\1\35\1\36\1\0"+
    "\2\2\2\0\1\6\1\37\2\40\2\0\1\41\1\0"+
    "\1\42\5\0\1\43\1\44\1\45\1\46\6\0\1\2"+
    "\1\6\1\0\1\47\10\0\1\2\13\0\1\50\5\0"+
    "\1\51\5\0\1\52\4\0\1\53\1\54\1\0\1\55"+
    "\1\0\1\56\1\57\1\60\10\0\1\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[153];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\160\0\340\0\160\0\160"+
    "\0\160\0\u0118\0\160\0\u0150\0\u0188\0\u01c0\0\u01f8\0\160"+
    "\0\160\0\u0230\0\u0268\0\u0188\0\160\0\u02a0\0\u02d8\0\u0310"+
    "\0\u0348\0\u0380\0\u03b8\0\160\0\160\0\160\0\160\0\160"+
    "\0\u03f0\0\u0428\0\160\0\160\0\u0460\0\u0498\0\u04d0\0\u0508"+
    "\0\u0540\0\u0578\0\u05b0\0\u05e8\0\u0620\0\u0658\0\u0690\0\u06c8"+
    "\0\u0700\0\u0738\0\u0770\0\u07a8\0\u07e0\0\u0818\0\u0850\0\u0888"+
    "\0\u08c0\0\u08f8\0\160\0\u0930\0\160\0\160\0\160\0\u0968"+
    "\0\160\0\160\0\u09a0\0\u09d8\0\u0a10\0\u0a48\0\u0a80\0\u0ab8"+
    "\0\u0540\0\u0af0\0\u0b28\0\u0620\0\u0b60\0\160\0\u0b98\0\u0540"+
    "\0\u0bd0\0\u0c08\0\u0c40\0\u0c78\0\u0cb0\0\u01f8\0\u01f8\0\u01f8"+
    "\0\u01f8\0\u0930\0\u0ce8\0\u0d20\0\u0a10\0\u0d58\0\u0d90\0\u0a48"+
    "\0\u0dc8\0\u0b28\0\u0e00\0\u0e38\0\u0e70\0\u0ea8\0\u0ee0\0\u0f18"+
    "\0\u0f50\0\u0f88\0\u0fc0\0\u0d58\0\u0ff8\0\u0e00\0\u1030\0\u1068"+
    "\0\u10a0\0\u10d8\0\u1110\0\u1148\0\u1180\0\u11b8\0\u11f0\0\160"+
    "\0\u1228\0\u1260\0\u1298\0\u12d0\0\u1308\0\160\0\u1340\0\u1378"+
    "\0\u13b0\0\u13e8\0\u1420\0\160\0\u1458\0\u1490\0\u14c8\0\u1500"+
    "\0\160\0\160\0\u1538\0\160\0\u1570\0\160\0\160\0\u15a8"+
    "\0\u15e0\0\u1618\0\u1650\0\u1688\0\u16c0\0\u16f8\0\u1730\0\u1768"+
    "\0\160";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[153];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\3\1\20\1\21"+
    "\1\22\1\3\1\23\1\14\1\17\1\24\1\25\1\14"+
    "\1\26\1\12\1\27\1\30\3\17\1\31\1\32\12\17"+
    "\1\33\1\17\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\3\1\17\1\14\23\43\1\44\41\43\1\45"+
    "\2\43\72\0\1\5\65\0\1\46\1\4\1\5\2\46"+
    "\1\47\62\46\10\0\1\50\1\51\17\0\2\50\44\0"+
    "\1\52\1\14\1\53\2\14\1\0\1\14\6\0\2\14"+
    "\2\0\3\14\1\0\22\14\10\0\2\14\10\0\1\54"+
    "\20\0\2\54\47\0\1\55\2\0\1\55\6\0\2\55"+
    "\2\0\1\55\3\0\22\55\10\0\2\55\7\0\1\56"+
    "\1\14\1\53\2\14\1\0\1\17\6\0\1\14\1\17"+
    "\2\0\3\14\1\0\22\17\10\0\1\17\1\14\22\57"+
    "\1\0\45\57\23\0\1\60\54\0\1\50\1\61\17\0"+
    "\2\50\71\0\1\62\4\0\1\63\1\0\1\64\2\0"+
    "\1\65\4\0\1\66\23\0\1\56\1\14\1\53\2\14"+
    "\1\0\1\17\6\0\1\14\1\17\2\0\3\14\1\0"+
    "\1\17\1\67\20\17\10\0\1\17\1\14\7\0\1\56"+
    "\1\14\1\53\2\14\1\0\1\17\6\0\1\14\1\17"+
    "\2\0\3\14\1\0\1\70\21\17\10\0\1\17\1\14"+
    "\7\0\1\56\1\14\1\53\2\14\1\0\1\17\6\0"+
    "\1\14\1\17\2\0\3\14\1\0\11\17\1\71\10\17"+
    "\10\0\1\17\1\14\7\0\1\56\1\14\1\53\2\14"+
    "\1\0\1\17\6\0\1\14\1\17\2\0\3\14\1\0"+
    "\21\17\1\72\10\0\1\17\1\14\63\0\1\73\16\0"+
    "\1\74\2\0\1\74\6\0\2\74\2\0\1\74\3\0"+
    "\22\74\10\0\2\74\23\0\1\75\11\0\1\76\6\0"+
    "\1\77\5\0\1\100\12\0\1\101\1\102\1\103\1\46"+
    "\1\4\1\5\65\46\1\47\1\104\1\105\1\47\1\106"+
    "\1\47\1\107\61\47\10\0\1\110\1\51\17\0\2\110"+
    "\45\0\1\111\20\0\2\111\45\0\1\112\1\0\1\113"+
    "\2\0\1\113\6\0\2\113\2\0\1\113\2\112\1\0"+
    "\22\113\10\0\2\113\10\0\1\14\1\53\2\14\1\0"+
    "\1\14\6\0\2\14\2\0\3\14\1\0\22\14\10\0"+
    "\2\14\10\0\1\54\1\51\17\0\2\54\45\0\1\55"+
    "\1\114\2\55\1\0\1\55\6\0\2\55\2\0\3\55"+
    "\1\0\22\55\10\0\2\55\10\0\1\112\1\0\1\113"+
    "\2\0\1\113\1\115\5\0\2\113\2\0\1\113\2\112"+
    "\1\0\22\113\10\0\2\113\22\57\1\116\45\57\23\0"+
    "\1\117\54\0\1\111\20\0\1\111\1\120\72\0\1\121"+
    "\67\0\1\122\66\0\1\123\77\0\1\124\57\0\1\125"+
    "\42\0\1\56\1\14\1\53\2\14\1\0\1\17\6\0"+
    "\1\14\1\17\2\0\3\14\1\0\4\17\1\126\15\17"+
    "\10\0\1\17\1\14\7\0\1\56\1\14\1\53\2\14"+
    "\1\0\1\17\6\0\1\14\1\17\2\0\3\14\1\0"+
    "\13\17\1\127\6\17\10\0\1\17\1\14\7\0\1\56"+
    "\1\14\1\53\2\14\1\0\1\17\6\0\1\14\1\17"+
    "\2\0\3\14\1\0\20\17\1\130\1\17\10\0\1\17"+
    "\1\14\7\0\1\56\1\14\1\53\2\14\1\0\1\17"+
    "\6\0\1\14\1\17\2\0\3\14\1\0\3\17\1\131"+
    "\16\17\10\0\1\17\1\14\10\0\1\74\1\132\2\74"+
    "\1\0\1\74\6\0\2\74\2\0\3\74\1\0\22\74"+
    "\10\0\2\74\10\0\1\133\13\0\2\133\3\0\2\133"+
    "\1\0\1\133\1\0\1\133\1\0\1\133\6\0\1\133"+
    "\4\0\1\133\23\0\1\134\13\0\2\134\3\0\2\134"+
    "\1\0\1\134\1\0\1\134\1\0\1\134\6\0\1\134"+
    "\4\0\1\134\13\0\2\135\1\105\1\135\1\136\1\135"+
    "\1\137\65\135\1\136\1\135\1\137\61\135\1\47\1\104"+
    "\1\105\1\47\1\106\64\47\1\104\1\105\1\47\1\140"+
    "\1\47\1\107\61\47\10\0\1\141\1\51\17\0\2\141"+
    "\45\0\1\112\1\0\2\112\1\0\1\112\6\0\2\112"+
    "\2\0\3\112\1\0\22\112\10\0\2\112\10\0\1\113"+
    "\1\142\2\113\1\0\1\113\6\0\2\113\2\0\3\113"+
    "\1\0\22\113\10\0\2\113\16\0\1\143\51\0\23\117"+
    "\1\144\44\117\36\0\1\145\67\0\1\146\75\0\1\147"+
    "\57\0\1\150\77\0\1\151\33\0\1\152\13\0\2\152"+
    "\3\0\2\152\1\0\1\152\1\0\1\152\1\0\1\152"+
    "\6\0\1\152\4\0\1\152\23\0\1\153\13\0\2\153"+
    "\3\0\2\153\1\0\1\153\1\0\1\153\1\0\1\153"+
    "\6\0\1\153\4\0\1\153\13\0\4\135\1\136\67\135"+
    "\1\154\1\135\1\137\61\135\10\0\1\54\1\51\1\0"+
    "\1\155\15\0\2\54\35\0\1\143\3\0\1\143\1\0"+
    "\3\143\1\156\5\143\1\156\1\0\47\143\23\117\1\157"+
    "\44\117\37\0\1\160\101\0\1\161\63\0\1\162\71\0"+
    "\1\163\62\0\1\164\35\0\1\165\13\0\2\165\3\0"+
    "\2\165\1\0\1\165\1\0\1\165\1\0\1\165\6\0"+
    "\1\165\4\0\1\165\23\0\1\166\13\0\2\166\3\0"+
    "\2\166\1\0\1\166\1\0\1\166\1\0\1\166\6\0"+
    "\1\166\4\0\1\166\23\0\1\167\20\0\2\167\35\0"+
    "\23\117\1\170\44\117\40\0\1\171\101\0\1\172\56\0"+
    "\1\173\67\0\1\174\62\0\1\175\43\0\1\176\13\0"+
    "\2\176\3\0\2\176\1\0\1\176\1\0\1\176\1\0"+
    "\1\176\6\0\1\176\4\0\1\176\23\0\1\177\13\0"+
    "\2\177\3\0\2\177\1\0\1\177\1\0\1\177\1\0"+
    "\1\177\6\0\1\177\4\0\1\177\23\0\1\200\20\0"+
    "\2\200\76\0\1\201\66\0\1\202\66\0\1\203\100\0"+
    "\1\204\72\0\1\205\24\0\1\206\13\0\2\206\3\0"+
    "\2\206\1\0\1\206\1\0\1\206\1\0\1\206\6\0"+
    "\1\206\4\0\1\206\26\0\1\207\111\0\1\210\66\0"+
    "\1\211\70\0\1\212\106\0\1\213\23\0\1\214\13\0"+
    "\2\214\3\0\2\214\1\0\1\214\1\0\1\214\1\0"+
    "\1\214\6\0\1\214\4\0\1\214\23\0\1\215\20\0"+
    "\2\215\77\0\1\216\73\0\1\217\31\0\1\220\20\0"+
    "\2\220\65\0\1\221\47\0\1\222\20\0\2\222\45\0"+
    "\1\223\20\0\2\223\44\0\1\224\70\0\1\225\20\0"+
    "\2\225\45\0\1\226\20\0\2\226\44\0\1\227\70\0"+
    "\1\230\20\0\2\230\45\0\1\231\20\0\2\231\35\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6048];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\1\1\3\11\1\1\1\11"+
    "\4\1\2\11\3\1\1\11\6\1\5\11\2\1\2\11"+
    "\1\1\2\0\1\1\3\0\2\1\11\0\4\1\1\11"+
    "\1\1\3\11\1\0\2\11\1\0\2\1\2\0\4\1"+
    "\2\0\1\11\1\0\1\1\5\0\4\1\6\0\2\1"+
    "\1\0\1\1\10\0\1\1\13\0\1\11\5\0\1\11"+
    "\5\0\1\11\4\0\2\11\1\0\1\11\1\0\2\11"+
    "\1\1\10\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[153];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private StringBuffer string = new StringBuffer(); // used to gather strings
  
  private String docuri;
  public void setDocuri(String docuri) {
    this.docuri = docuri;
  }
  
  public Token nextToken() {
    try {
      return nextToken2();
    } catch (java.io.IOException e) {
      // FIXME: is this OK?
      return new CommonToken(Token.EOF_TYPE, "END OF FUCKING FILE, OK?");
    }
  }
  
  private Token newToken(int type, String text) {
    CommonToken token = new CommonToken(type, text);
    token.setLine(yyline + 1);
    token.setColumn(yycolumn);
    return token;
  }

  private Token newToken(int type) {
    return newToken(type, yytext());
  }

  private char unhex(int length) {
    int number = 0;
    for (int ix = 0; ix < length; ix++) {
      int digit;
      char ch = yycharat(2 + ix);
      if (ch >= '0' && ch <= '9')
        digit = ch - '0';
      else if (ch >= 'a' && ch <= 'f')
        digit = (ch - 'a') + 10;
      else if (ch >= 'A' && ch <= 'F')
        digit = (ch - 'A') + 10;
      else
        throw new InvalidTopicMapException("Invalid escape sequence: '" +
                                           yytext() + "'");
    
      number = number * 16 + digit;
    }
    return (char) number;
  }  


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public CTMLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public CTMLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 142) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token nextToken2() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 41: 
          { string.append(unhex(4));
          }
        case 50: break;
        case 2: 
          { /* ignore */
          }
        case 51: break;
        case 4: 
          { return newToken(CTMParser.RIGHTPAREN);
          }
        case 52: break;
        case 7: 
          { return newToken(CTMParser.STOP);
          }
        case 53: break;
        case 34: 
          { return newToken(CTMParser.ONEOH);
          }
        case 54: break;
        case 27: 
          { string.append((char) 10);
          }
        case 55: break;
        case 3: 
          { return newToken(CTMParser.LEFTPAREN);
          }
        case 56: break;
        case 18: 
          { return newToken(CTMParser.LEFTBRACKET);
          }
        case 57: break;
        case 16: 
          { return newToken(CTMParser.EQUALS);
          }
        case 58: break;
        case 37: 
          { return newToken(CTMParser.ISA);
          }
        case 59: break;
        case 43: 
          { return newToken(CTMParser.INCLUDE);
          }
        case 60: break;
        case 36: 
          { return newToken(CTMParser.DEF);
          }
        case 61: break;
        case 10: 
          { return newToken(CTMParser.SEMICOLON);
          }
        case 62: break;
        case 22: 
          { yybegin(YYINITIAL);
       return newToken(CTMParser.SINGLE_QUOTED_STRING, string.toString());
          }
        case 63: break;
        case 24: 
          { return newToken(CTMParser.HATHAT);
          }
        case 64: break;
        case 40: 
          { return newToken(CTMParser.TRIPLE_QUOTED_STRING,
                                     yytext().substring(3, yylength() - 3));
          }
        case 65: break;
        case 12: 
          { string.setLength(0); // empty string buffer
                     yybegin(STRING);
          }
        case 66: break;
        case 26: 
          { string.append('"');
          }
        case 67: break;
        case 29: 
          { string.append('\\');
          }
        case 68: break;
        case 6: 
          { return newToken(CTMParser.INTEGER);
          }
        case 69: break;
        case 14: 
          { return newToken(CTMParser.COMMA);
          }
        case 70: break;
        case 44: 
          { return newToken(CTMParser.VERSION);
          }
        case 71: break;
        case 38: 
          { return newToken(CTMParser.AKO);
          }
        case 72: break;
        case 17: 
          { return newToken(CTMParser.TILDE);
          }
        case 73: break;
        case 13: 
          { return newToken(CTMParser.INFINITY);
          }
        case 74: break;
        case 21: 
          { string.append(yycharat(0));
          }
        case 75: break;
        case 42: 
          { return newToken(CTMParser.PREFIX);
          }
        case 76: break;
        case 49: 
          { return newToken(CTMParser.DATETIME);
          }
        case 77: break;
        case 11: 
          { return newToken(CTMParser.RIGHTBRACKET);
          }
        case 78: break;
        case 9: 
          { return newToken(CTMParser.HYPHEN);
          }
        case 79: break;
        case 33: 
          { return newToken(CTMParser.WRAPPED_IRI,
                                     yytext().substring(1, yylength() - 1));
          }
        case 80: break;
        case 8: 
          { return newToken(CTMParser.IDENTIFIER);
          }
        case 81: break;
        case 32: 
          { return newToken(CTMParser.QNAME);
          }
        case 82: break;
        case 28: 
          { string.append((char) 13);
          }
        case 83: break;
        case 39: 
          { return newToken(CTMParser.IRI);
          }
        case 84: break;
        case 48: 
          { return newToken(CTMParser.DATE);
          }
        case 85: break;
        case 1: 
          { throw new InvalidTopicMapException("Illegal character <"+yytext()+"> at " +
                                     docuri + ":" + (yyline+1) + ":" + yycolumn);
          }
        case 86: break;
        case 19: 
          { return newToken(CTMParser.HAT);
          }
        case 87: break;
        case 25: 
          { return newToken(CTMParser.NAMED_WILDCARD,
                                     yytext().substring(1));
          }
        case 88: break;
        case 45: 
          { string.append(unhex(6));
          }
        case 89: break;
        case 35: 
          { return newToken(CTMParser.END);
          }
        case 90: break;
        case 15: 
          { return newToken(CTMParser.AT);
          }
        case 91: break;
        case 23: 
          { return newToken(CTMParser.VARIABLE);
          }
        case 92: break;
        case 30: 
          { string.append((char) 9);
          }
        case 93: break;
        case 20: 
          { return newToken(CTMParser.WILDCARD);
          }
        case 94: break;
        case 47: 
          { return newToken(CTMParser.MERGEMAP);
          }
        case 95: break;
        case 46: 
          { return newToken(CTMParser.ENCODING);
          }
        case 96: break;
        case 31: 
          { return newToken(CTMParser.DECIMAL);
          }
        case 97: break;
        case 5: 
          { return newToken(CTMParser.COLON);
          }
        case 98: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {
                return newToken(CTMParser.EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
