name: Build

on:
  push:
  pull_request:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version-file: '.java-version'
        cache: maven

    - name: Build with Maven
      run: mvn -B -Dstyle.color=always package -Pontopia-distribution-tomcat -Pcoverage

    - name: Save test coverage
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: '**/jacoco.xml'

    - name: Build with Docker
      run: docker build .
