name: Java CI

on: 
  push:
  pull_request:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version-file: '.java-version'
        cache: 'maven'
    - name: Restore Maven cache
      uses: skjolber/maven-cache-github-action@v3.1.1
      with:
        step: restore
    - name: Build with Maven
      run: mvn -B -Dstyle.color=always package --file pom.xml
    - name: Save Maven cache
      uses: skjolber/maven-cache-github-action@v3.1.1
      with:
        step: save
