name: Publish release

on:
  push:
    tags:
      - 'release-**'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:


      # --- Prepare

      - uses: actions/checkout@v6
        with:
          fetch-tags: true

      - name: Resolve version
        run: |
          git tag --sort=-creatordate | grep -A 1 ${{ github.ref_name }}
          ref="${{ github.ref_name }}"
          version="${ref#"release-"}"
          prevref=`git tag --sort=-creatordate | grep -A 1 ${{ github.ref_name }} | tail -n 1`
          prevversion="${ref#"release-"}"
          echo "VERSION=$version" >> "$GITHUB_ENV"
          echo "PREVIOUS=$prevversion" >> "$GITHUB_ENV"
          echo "version = $version, previous = $prevversion"

      - name: Set up Maven
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version-file: '.java-version'
          cache: maven


      # --- Distribution zip

      - name: Build distribution
        run: |
          mvn -B -Dstyle.color=always verify -Pontopia-distribution-tomcat -DskipTests -Djetty.skip=true
          mv ontopia-distribution-tomcat/target/ontopia-distribution-tomcat-*.zip ontopia-$VERSION.zip

      - name: Save distribution
        uses: actions/upload-artifact@v7
        with:
          name: ontopia-${{env.VERSION}}.zip
          path: ontopia-${{env.VERSION}}.zip


      # --- Github release

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          name: Ontopia ${{env.VERSION}}
          files: ontopia-${{env.VERSION}}.zip
          body: |
            [Release notes](https://ontopia.net/doc/${{env.VERSION}}/whatsnew.html)

            **Full Changelog**: https://github.com/ontopia/ontopia/compare/release-${{env.PREVIOUS}}...release-${{env.VERSION}}
