name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version to release
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Set up Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version-file: '.java-version'
        server-id: ossrh
        server-username: MAVEN_CENTRAL_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: GPG_PASSPHRASE
        cache: maven

    - name: Publish to Apache Maven Central
      run: |
        mvn -B -Dstyle.color=always release:prepare -DreleaseVersion=${{ github.event.inputs.version }}
        mvn -B -Dstyle.color=always release:perform -DdeploymentName="Release ${{ github.event.inputs.version }}"
      env:
        MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
